# Generated by Django 2.0.7 on 2018-08-26 13:29

import datetime
from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('acc_num', models.CharField(max_length=30)),
                ('rial_wallet', models.FloatField(default=0)),
                ('dollar_wallet', models.FloatField(default=0)),
                ('euro_wallet', models.FloatField(default=0)),
                ('salary', models.FloatField(default=0)),
                ('dollor_account', models.CharField(max_length=30)),
                ('euro_account', models.CharField(max_length=30)),
                ('status', models.CharField(default='enabled', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GREForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('center', models.CharField(max_length=200)),
                ('placecode', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('citizen', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('majorcode', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IELTSForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 26, 13, 29, 0, 621890, tzinfo=utc))),
                ('subject', models.CharField(default='موضوع', max_length=30)),
                ('content', models.TextField(default='محتوا')),
            ],
        ),
        migrations.CreateModel(
            name='PayForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('arzi', models.FloatField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TOEFLForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('center', models.CharField(max_length=200)),
                ('placecode', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('citizen', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('majorcode', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('destination', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 8, 26, 13, 29, 0, 620889, tzinfo=utc))),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2018, 8, 27, 13, 29, 0, 620889, tzinfo=utc))),
                ('type', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='در حال انتظار', max_length=30)),
                ('subject', models.CharField(default='موضوع', max_length=30)),
                ('content', models.CharField(default='محتوا', max_length=300)),
                ('greform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.GREForm')),
                ('ieltsform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.IELTSForm')),
                ('payform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PayForm')),
                ('toeflform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.TOEFLForm')),
            ],
        ),
        migrations.CreateModel(
            name='UniForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site', models.URLField()),
                ('process', models.TextField()),
                ('arzi', models.FloatField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salarry', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.myuser', django.contrib.auth.base_user.BaseUserManager),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dollor_accouunt', models.CharField(default='شماره حساب دلار', max_length=30)),
                ('euro_accouunt', models.CharField(default='شماره حساب یورو', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.myuser', django.contrib.auth.base_user.BaseUserManager),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UniForm'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karbar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferestande', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='girande', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karmand', to='blog.Employee'),
        ),
    ]
