# Generated by Django 2.0.7 on 2018-08-26 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180826_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 13, 41, 29, 657808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 13, 41, 29, 656808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 13, 41, 29, 656808, tzinfo=utc)),
        ),
    ]
