# Generated by Django 2.0.7 on 2018-08-26 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180826_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 13, 42, 23, 909292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 13, 42, 23, 908292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 13, 42, 23, 908292, tzinfo=utc)),
        ),
    ]
